// ── Static arrays ─────────────────────────────────────────────────────────────

const artistPaves1030 = [
    "Ingrid Schreyers",
    "Nadine Jourde",
    "Rita Dooms",
    "Saskia Leurart",
    "Whitney Orville",
    "pour déterminer"
];

const streetFR1030 = [
    "allée des freesias",
    "avenue adolphe lacomblé",
    "avenue albert desenfans",
    "avenue albert giraud",
    "avenue ambassadeur van vollenhoven",
    "avenue britsiers",
    "avenue charbo",
    "avenue charles gilisquet",
    "avenue chazal",
    "avenue clays",
    "avenue colonel picquart",
    "avenue dailly",
    "avenue de la brabançonne",
    "avenue de la reine",
    "avenue de la topaze",
    "avenue de l'emeraude",
    "avenue de l'héliport",
    "avenue de l'opale",
    "avenue de mars",
    "avenue de roodebeek",
    "avenue des azalées",
    "avenue des capucines",
    "avenue des cerisiers",
    "avenue des clos",
    "avenue des glycines",
    "avenue des héliotropes",
    "avenue des jacinthes",
    "avenue des jardins",
    "avenue docteur dejase",
    "avenue du cimetière",
    "avenue du diamant",
    "avenue du suffrage universel",
    "avenue emile max",
    "avenue emile verhaeren",
    "avenue emile zola",
    "avenue ernest cambier",
    "avenue ernest renan",
    "avenue eugène demolder",
    "avenue eugène plasky",
    "avenue félix marchal",
    "avenue fortin",
    "avenue frans courtens",
    "avenue général eisenhower",
    "avenue georges eekhoud",
    "avenue georges rodenbach",
    "avenue gustave latinis",
    "avenue herbert hoover",
    "avenue huart hamoir",
    "avenue jacques georgin",
    "avenue jan stobbaerts",
    "avenue jean jaurès",
    "avenue léon mahillon",
    "avenue louis bertrand",
    "avenue maréchal foch",
    "avenue maurice maeterlinck",
    "avenue milcamps",
    "avenue monplaisir",
    "avenue paul deschanel",
    "avenue princesse elisabeth",
    "avenue raymond foucart",
    "avenue rogier",
    "avenue sleeckx",
    "avenue voltaire",
    "avenue zénobe gramme",
    "boulevard auguste reyers",
    "boulevard du roi albert ii",
    "boulevard général wahis",
    "boulevard lambermont",
    "boulevard léopold iii",
    "boulevard simon bolivar",
    "chaussée de haecht",
    "chaussée de helmet",
    "chaussée de louvain",
    "cité ouvrière de linthout",
    "clos des mouettes",
    "clos du chemin creux",
    "grande rue au bois",
    "non renseigné",
    "parc rasquinet",
    "petite rue l'olivier",
    "place colignon",
    "place colonel bremer",
    "place dailly",
    "place de helmet",
    "place de houffalize",
    "place de jamblinne de meux",
    "place de la patrie",
    "place de la reine",
    "place des bienfaiteurs",
    "place des carabiniers",
    "place des chasseurs ardennais",
    "place du pavillon",
    "place eugène verboekhoven",
    "place gaucheret",
    "place général meiser",
    "place lehon",
    "place liedts",
    "place masui",
    "place pogge",
    "place princesse elisabeth",
    "place solvay",
    "place stephenson",
    "place terdelt",
    "place wappers",
    "rue achille detienne",
    "rue adolphe marbotin",
    "rue aimé smekens",
    "rue albert de latour",
    "rue alexandre de craene",
    "rue alexandre markelbach",
    "rue allard",
    "rue anatole france",
    "rue andré van hasselt",
    "rue armand de roo",
    "rue artan",
    "rue arthur roland",
    "rue auguste lambiotte",
    "rue auguste snieders",
    "rue brichaut",
    "rue camille simoens",
    "rue camille wollès",
    "rue caporal claes",
    "rue capronnier",
    "rue charles meert",
    "rue charles van lerberghe",
    "rue charles vanderstappen",
    "rue chaumontel",
    "rue colonel bourg",
    "rue cornet de grez",
    "rue creuse",
    "rue d'aerschot",
    "rue d'anethan",
    "rue de beughem",
    "rue de brabant",
    "rue de cologne",
    "rue de genève",
    "rue de jérusalem",
    "rue de la bruyère",
    "rue de la chaumière",
    "rue de la cible",
    "rue de la consolation",
    "rue de la constitution",
    "rue de la fraternité",
    "rue de la luzerne",
    "rue de la marne",
    "rue de la poste",
    "rue de la ruche",
    "rue de l'agriculture",
    "rue de l'est",
    "rue de linthout",
    "rue de locht",
    "rue de l'orme",
    "rue de moerkerke",
    "rue de potter",
    "rue de quatrecht",
    "rue de robiano",
    "rue des ailes",
    "rue des chardons",
    "rue des compagnons",
    "rue des coteaux",
    "rue des mimosas",
    "rue des palais",
    "rue des pâquerettes",
    "rue des pavots",
    "rue des pensées",
    "rue des plantes",
    "rue désiré desmet",
    "rue destouvelles",
    "rue d'hoogvorst",
    "rue docteur elie lambotte",
    "rue du 150e anniversaire, 24",
    "rue du corbeau",
    "rue du dahlia",
    "rue du foyer schaerbeekois",
    "rue du noyer",
    "rue du pavillon",
    "rue du progrès",
    "rue du radium",
    "rue du saphir",
    "rue du tilleul",
    "rue dupont",
    "rue edouard fiers",
    "rue emile wittmann",
    "rue emmanuel hiel",
    "rue ernest discailles",
    "rue ernest laude",
    "rue eugène smits",
    "rue fernand séverin",
    "rue floris",
    "rue fontaine d'amour",
    "rue fraikin",
    "rue françois bossaerts",
    "rue français degreef",
    "rue français-joseph navez",
    "rue frans binjé",
    "rue frédéric pelletier",
    "rue gallait",
    "rue gaucheret",
    "rue geefs",
    "rue gendebien",
    "rue général eenens",
    "rue général gratry",
    "rue georges garnir",
    "rue georges raeymaekers",
    "rue godefroid devreese",
    "rue godefroid guffens",
    "rue goossens",
    "rue grégoire leroy",
    "rue guido gezelle",
    "rue guillaume kennis",
    "rue gustave fuss",
    "rue gustave huberti",
    "rue hancart",
    "rue henri bergé",
    "rue henri chomé",
    "rue henri evenepoel",
    "rue henri jacobs",
    "rue henri stacquet",
    "rue henry villard",
    "rue herman",
    "rue herman richir",
    "rue hubert krains",
    "rue iwan gilkin",
    "rue jacques jansen",
    "rue jacques rayé",
    "rue james watt",
    "rue jan blockx",
    "rue jenatzy",
    "rue jolly",
    "rue josaphat",
    "rue joseph brand",
    "rue joseph coosemans",
    "rue joseph jacquet",
    "rue joseph van camp",
    "rue joseph wauters",
    "rue josse impens",
    "rue jules destrée",
    "rue jules lebrun",
    "rue kessels",
    "rue knapen",
    "rue lefrancq",
    "rue léon frédéric",
    "rue léon mignon",
    "rue léopold courouble",
    "rue liedts",
    "rue linné",
    "rue l'olivier",
    "rue louis scutenaire",
    "rue louis socquet",
    "rue marcel mariën",
    "rue marguerite van de wiele",
    "rue massaux",
    "rue masui",
    "rue maurice des ombiaux",
    "rue max roos",
    "rue metsys",
    "rue monrose",
    "rue nestor de tière",
    "rue nicolas defrêcheux",
    "rue paul devigne",
    "rue paul hymans",
    "rue paul leduc",
    "rue philomène",
    "rue pierre mattheussens",
    "rue pierre theunis",
    "rue portaels",
    "rue potagère",
    "rue quinaux",
    "rue rasson",
    "rue renkin",
    "rue richard vandevelde",
    "rue roelandts",
    "rue rogier",
    "rue royale",
    "rue royale-sainte-marie",
    "rue rubens",
    "rue sander pierron",
    "rue seutin",
    "rue stephenson",
    "rue stijn streuvels",
    "rue teniers",
    "rue théo coopman",
    "rue théodore roosevelt",
    "rue thiéfry",
    "rue thomas vinçotte",
    "rue van droogenbroeck",
    "rue van dyck",
    "rue van hammée",
    "rue van hoorde",
    "rue van hove",
    "rue van oost",
    "rue van schoor",
    "rue van ysendyck",
    "rue vandenbussche",
    "rue vanderlinden",
    "rue vandermeersch",
    "rue vandeweyer",
    "rue verbist",
    "rue verboeckhaven",
    "rue vergote",
    "rue verhas",
    "rue verte",
    "rue verwée",
    "rue victor hugo",
    "rue victor lefèvre",
    "rue victor oudart",
    "rue victor vanderhoeft",
    "rue vifquin",
    "rue vogler",
    "rue vonck",
    "rue vondel",
    "rue waelhem",
    "rue willem kuhnen",
    "rue william degouve de nuncques",
    "square apollo",
    "square emile duployé",
    "square eugène plasky",
    "square français riga",
    "square levie",
    "square prévost-delaunay",
    "square vergote"
];

const streetNL1030 = [
    "freesiadreef",
    "adolphe lacomblélaan",
    "albert desenfanslaan",
    "albert giraudlaan",
    "ambassadeur van vollenhovenlaan",
    "britsierslaan",
    "charbolaan",
    "charles gilisquetlaan",
    "chazallaan",
    "clayslaan",
    "kolonel picquartlaan",
    "daillylaan",
    "brabançonnelaan",
    "koninginnelaan",
    "topaaslaan",
    "smaragdlaan",
    "helihavenlaan",
    "opaallaan",
    "maartlaan",
    "roodebeeklaan",
    "azalealaan",
    "kapucijnbloemenlaan",
    "kerselarenlaan",
    "gaardenlaan",
    "blauweregenlaan",
    "heliotropenlaan",
    "hyacintenlaan",
    "bloemtuinenlaan",
    "dokter dejaselaan",
    "kerkhof van brussellaan",
    "diamantlaan",
    "algemeen stemrechtlaan",
    "emile maxlaan",
    "emile verhaerenlaan",
    "emile zolalaan",
    "ernest cambierlaan",
    "ernest renanlaan",
    "eugène demolderlaan",
    "eugène plaskylaan",
    "félix marchallaan",
    "fortinlaan",
    "frans courtenslaan",
    "generaal eisenhowerlaan",
    "georges eekhoudlaan",
    "georges rodenbachlaan",
    "gustave latinislaan",
    "herbert hooverlaan",
    "huart hamoirlaan",
    "jacques georginlaan",
    "jan stobbaertslaan",
    "jean jaurèslaan",
    "léon mahillonlaan",
    "louis bertrandlaan",
    "maarschalk fochlaan",
    "maurice maeterlincklaan",
    "milcampslaan",
    "monplaisirlaan",
    "paul deschanellaan",
    "prinses elisabethlaan",
    "raymond foucartlaan",
    "rogierlaan",
    "sleeckxlaan",
    "voltairelaan",
    "zénobe grammelaan",
    "auguste reyerslaan",
    "koning albert ii laan",
    "generaal wahislaan",
    "lambermontlaan",
    "leopold iii-laan",
    "simon bolivarlaan",
    "haachtsesteenweg",
    "helmetsesteenweg",
    "leuvensesteenweg",
    "linthoutse werkmanswoonwijk",
    "meeuwengaarde",
    "holleweggaarde",
    "grote bosstraat",
    "niet gespecificeerd",
    "rasquinetpark",
    "korte l'olivierstraat",
    "colignonplein",
    "kolonel bremerplein",
    "daillyplein",
    "helmetseplein",
    "houffalizeplein",
    "de jamblinne de meuxplein",
    "vaderlandsplein",
    "koninginneplein",
    "weldoenersplein",
    "karabiniersplein",
    "ardense jagersplein",
    "paviljoenplein",
    "eugène verboekhovenplein",
    "gaucheretplein",
    "generaal meiserplein",
    "lehonplein",
    "liedtsplein",
    "masuiplein",
    "poggeplein",
    "prinses elisabethplein",
    "solvayplein",
    "stephensonplein",
    "terdeltplein",
    "wappersplein",
    "achille detiennestraat",
    "adolphe marbotinstraat",
    "aimé smekensstraat",
    "albert de latourstraat",
    "alexandre de craenestraat",
    "alexandre markelbachstraat",
    "allardstraat",
    "anatole francestraat",
    "andré van hasseltstraat",
    "armand de roostraat",
    "artanstraat",
    "arthur rolandstraat",
    "auguste lambiottestraat",
    "auguste sniedersstraat",
    "brichautstraat",
    "camille simoensstraat",
    "camille wollèsstraat",
    "korporaal claesstraat",
    "capronnierstraat",
    "charles meertstraat",
    "charles van lerberghestraat",
    "charles vanderstappenstraat",
    "chaumontelstraat",
    "kolonel bourgstraat",
    "cornet de grezstraat",
    "hollestraat",
    "aarschotstraat",
    "d'anethanstraat",
    "de beughemstraat",
    "brabantstraat",
    "keulenstraat",
    "genèvestraat",
    "jerusalemstraat",
    "heidestraat",
    "hutstraat",
    "schietschijfstraat",
    "trooststraat",
    "grondwetstraat",
    "broederschapstraat",
    "luzernestraat",
    "marnestraat",
    "poststraat",
    "bijenkorfstraat",
    "landbouwstraat",
    "ooststraat",
    "linthoutstraat",
    "de lochtstraat",
    "olmstraat",
    "de moerkerkestraat",
    "de potterstraat",
    "kwatrechtstraat",
    "de robianostraat",
    "vleugelsstraat",
    "distelsstraat",
    "gezellenstraat",
    "wijnheuvelenstraat",
    "mimosasstraat",
    "paleizenstraat",
    "madeliefjesstraat",
    "papaverstraat",
    "penseestraat",
    "plantenstraat",
    "désiré desmetstraat",
    "destouvellesstraat",
    "d'hoogvorststraat",
    "dokter elie lambottestraat",
    "niet gespecificeerd",
    "raafstraat",
    "dahliastraat",
    "schaarbeekse haardstraat",
    "notelaarstraat",
    "paviljoenstraat",
    "vooruitgangstraat",
    "radiumstraat",
    "saffierstraat",
    "lindestraat",
    "dupontstraat",
    "edouard fiersstraat",
    "emile wittmannstraat",
    "emmanuel hielstraat",
    "ernest discaillesstraat",
    "ernest laudestraat",
    "eugène smitsstraat",
    "fernand séverinstraat",
    "florisstraat",
    "minnebronstraat",
    "fraikinstraat",
    "français bossaertsstraat",
    "français degreefstraat",
    "français-joseph navezstraat",
    "frans binjéstraat",
    "frédéric pelletierstraat",
    "gallaitstraat",
    "gaucheretstraat",
    "geefsstraat",
    "gendebienstraat",
    "generaal eenensstraat",
    "generaal gratrystraat",
    "georges garnirstraat",
    "georges raeymaekersstraat",
    "godefroid devreesestraat",
    "godefroid guffensstraat",
    "goossensstraat",
    "grégoire leroystraat",
    "guido gezellestraat",
    "guillaume kennisstraat",
    "gustave fussstraat",
    "gustave hubertistraat",
    "hancartstraat",
    "henri bergéstraat",
    "henri choméstraat",
    "henri evenepoelstraat",
    "henri jacobsstraat",
    "henri stacquetstraat",
    "henry villardstraat",
    "hermanstraat",
    "herman richirstraat",
    "hubert krainsstraat",
    "iwan gilkinstraat",
    "jacques jansenstraat",
    "jacques rayéstraat",
    "james wattstraat",
    "jan blockxstraat",
    "jenatzystraat",
    "jollystraat",
    "josafatstraat",
    "joseph brandstraat",
    "joseph coosemansstraat",
    "joseph jacquetstraat",
    "joseph van campstraat",
    "joseph wautersstraat",
    "josse impensstraat",
    "jules destréestraat",
    "jules lebrunstraat",
    "kesselsstraat",
    "knapenstraat",
    "lefrancqstraat",
    "léon frédéricstraat",
    "léon mignonstraat",
    "léopold couroublestraat",
    "liedtsstraat",
    "linnéstraat",
    "l'olivierstraat",
    "louis scutenairestraat",
    "louis socquetstraat",
    "marcel mariënstraat",
    "marguerite van de wielestraat",
    "massauxstraat",
    "masuistraat",
    "maurice des ombiauxstraat",
    "max roosstraat",
    "metsysstraat",
    "monrosestraat",
    "nestor de tièrestraat",
    "nicolas defrêcheuxstraat",
    "paul devignestraat",
    "paul hymansstraat",
    "paul leducstraat",
    "philomènestraat",
    "rue pierre mattheussens",
    "pierre theunisstraat",
    "portaelsstraat",
    "warmoesstraat",
    "quinauxstraat",
    "rassonstraat",
    "renkinstraat",
    "richard vandeveldestraat",
    "roelandtsstraat",
    "rogierstraat",
    "koningsstraat",
    "koninklijke sinte-mariastraat",
    "rubensstraat",
    "sander pierronstraat",
    "seutinstraat",
    "stephensonstraat",
    "stijn streuvelsstraat",
    "teniersstraat",
    "théo coopmanstraat",
    "théodore rooseveltstraat",
    "thiéfrystraat",
    "thomas vinçottestraat",
    "van droogenbroeckstraat",
    "van dyckstraat",
    "van hamméestraat",
    "van hoordestraat",
    "van hovestraat",
    "van ooststraat",
    "van schoorstraat",
    "van ysendyckstraat",
    "vandenbusschestraat",
    "vanderlindenstraat",
    "vandermeerschstraat",
    "vandeweyerstraat",
    "verbiststraat",
    "verboeckhavenstraat",
    "vergotestraat",
    "verhasstraat",
    "groenstraat",
    "verwéestraat",
    "victor hugostraat",
    "victor lefèvrestraat",
    "victor oudartstraat",
    "victor vanderhoeftstraat",
    "vifquinstraat",
    "voglerstraat",
    "vonckstraat",
    "vondelstraat",
    "waelhemstraat",
    "willem kuhnenstraat",
    "william degouve de nuncquesstraat",
    "apollosquare",
    "emile duployésquare",
    "eugène plaskysquare",
    "français rigasquare",
    "leviesquare",
    "prévost-delaunaysquare",
    "vergotesquare"
];

// ── Functions ─────────────────────────────────────────────────────────────────

// Populates a <datalist> element with options from an array
function populateDatalist(listId, dataArray) {
    const datalist = document.getElementById(listId);
    if (datalist) {
        datalist.innerHTML = "";
        dataArray.forEach(item => {
            const option = document.createElement('option');
            option.value = item;
            datalist.appendChild(option);
        });
    } else {
        console.error(`Datalist con ID "${listId}" no encontrado.`);
    }
}

// Extracts unique sorted values of a property from one or more GeoJSON sources
function ListaPropiedad(nombrePropiedad, origenDatos) {
    const valoresUnicos = new Set();
    const fuentes = Array.isArray(origenDatos) ? origenDatos : [origenDatos];
    fuentes.forEach(fuente => {
        if (fuente && fuente.features) {
            fuente.features.forEach(feature => {
                const valor = feature.properties[nombrePropiedad];
                if (valor !== undefined && valor !== null && valor !== "") {
                    valoresUnicos.add(valor);
                }
            });
        }
    });
    return Array.from(valoresUnicos).sort();
}

// ── Dynamic extraction from ListePavesMosaiques1030 ───────────────────────────

const streetFR_paves = ListaPropiedad("StreetFR", [ListePavesMosaiques1030]);
document.addEventListener('DOMContentLoaded', (event) => {
    populateDatalist('datalist_StreetFR', streetFR_paves);
});

const streetNL_paves = ListaPropiedad("StreetNL", [ListePavesMosaiques1030]);
document.addEventListener('DOMContentLoaded', (event) => {
    populateDatalist('datalist_StreetNL', streetNL_paves);
});

const artist_paves = ListaPropiedad("Artist", [ListePavesMosaiques1030]);
document.addEventListener('DOMContentLoaded', (event) => {
    populateDatalist('datalist_Artist', artist_paves);
});

const sector_paves = ListaPropiedad("Sector", [ListePavesMosaiques1030]);
document.addEventListener('DOMContentLoaded', (event) => {
    populateDatalist('datalist_Sector', sector_paves);
});

const year_paves = ListaPropiedad("Year", [ListePavesMosaiques1030]);
document.addEventListener('DOMContentLoaded', (event) => {
    populateDatalist('datalist_Year', year_paves);
});

const status_paves = ListaPropiedad("Status", [ListePavesMosaiques1030]);
document.addEventListener('DOMContentLoaded', (event) => {
    populateDatalist('datalist_Status', status_paves);
});
